version: "3.2"

services:
  ssh-jumpbox1:
    image: monsoft/ssh-jumpbox
    hostname: jumpbox1
    environment:
      USERS: 'test1 test2'
    ports:
      - "1022:22"
    networks:
      - jumpbox1
    volumes:
      - ssh-jumpbox1:/home
      - /opt/sshkeys/jumpbox1:/etc/authorized-keys
    deploy:
      mode: replicated
      replicas: 2

volumes:
  ssh-jumpbox1:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=192.168.56.130,nolock,soft,rw"
      device: ":/docker_data/jumpbox1"

networks:
  jumpbox1:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 172.28.1.0/29
